---
- name: Update apt cache securely
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Prometheus Node Exporter natively via APT package manager
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Prometheus Node Exporter service is fully enabled and running
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
