---
- name: Manage App Directory Structure
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Deploy application source code
  copy:
    src: ../app/index.html
    dest: /home/ubuntu/app/index.html
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Ensure dynamic container environment is fully synchronized
  community.docker.docker_container:
    name: devops-web-app
    image: nginx:alpine
    state: started
    restart: yes
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app/index.html:/usr/share/nginx/html/index.html
