plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: [ 'running' ]
  tag:Project: aws-devops-automation

keyed_groups:
  - key: tags.Role
    prefix: tags_Role

hostnames:
  - public-ip-address
