---
- name: Update apt index securely
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install required baseline packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present

- name: Install Docker Engine and Compose Plugin
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Ensure Docker is enabled on boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
